name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-from-Markdown:
    name: Build Static Files from Markdown
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation using MkDocs
        run: mkdocs build

  Deploy-Preview:
    name: Deploy to Preview
    runs-on: ubuntu-22.04
    needs: [Build-from-Markdown]
    if: github.ref != 'refs/heads/main' && ((github.event_name == 'pull_request' && github.head_ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch')
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Production:
    name: Deploy to Production
    runs-on: ubuntu-22.04
    needs: [Build-from-Markdown]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
